/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrandedGiftsRouteImport } from './routes/branded-gifts'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CorporateBrandingRouteImport } from './routes/corporate-branding'
import { Route as FabricPrintingRouteImport } from './routes/fabric-printing'
import { Route as MadeToOrderRouteImport } from './routes/made-to-order'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SizingFramingRouteImport } from './routes/sizing-framing'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as PrintDesignsIndexRouteImport } from './routes/print-designs.index'
import { Route as PrintDesignsSlugRouteImport } from './routes/print-designs.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandedGiftsRoute = BrandedGiftsRouteImport.update({
  id: '/branded-gifts',
  path: '/branded-gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateBrandingRoute = CorporateBrandingRouteImport.update({
  id: '/corporate-branding',
  path: '/corporate-branding',
  getParentRoute: () => rootRouteImport,
} as any)
const FabricPrintingRoute = FabricPrintingRouteImport.update({
  id: '/fabric-printing',
  path: '/fabric-printing',
  getParentRoute: () => rootRouteImport,
} as any)
const MadeToOrderRoute = MadeToOrderRouteImport.update({
  id: '/made-to-order',
  path: '/made-to-order',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SizingFramingRoute = SizingFramingRouteImport.update({
  id: '/sizing-framing',
  path: '/sizing-framing',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const PrintDesignsIndexRoute = PrintDesignsIndexRouteImport.update({
  id: '/print-designs/',
  path: '/print-designs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintDesignsSlugRoute = PrintDesignsSlugRouteImport.update({
  id: '/print-designs/$slug',
  path: '/print-designs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branded-gifts': typeof BrandedGiftsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/corporate-branding': typeof CorporateBrandingRoute
  '/fabric-printing': typeof FabricPrintingRoute
  '/made-to-order': typeof MadeToOrderRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/shipping': typeof ShippingRoute
  '/sizing-framing': typeof SizingFramingRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/print-designs/$slug': typeof PrintDesignsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/print-designs/': typeof PrintDesignsIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branded-gifts': typeof BrandedGiftsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/corporate-branding': typeof CorporateBrandingRoute
  '/fabric-printing': typeof FabricPrintingRoute
  '/made-to-order': typeof MadeToOrderRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/shipping': typeof ShippingRoute
  '/sizing-framing': typeof SizingFramingRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/print-designs/$slug': typeof PrintDesignsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/print-designs': typeof PrintDesignsIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/branded-gifts': typeof BrandedGiftsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/corporate-branding': typeof CorporateBrandingRoute
  '/fabric-printing': typeof FabricPrintingRoute
  '/made-to-order': typeof MadeToOrderRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/shipping': typeof ShippingRoute
  '/sizing-framing': typeof SizingFramingRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/print-designs/$slug': typeof PrintDesignsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/print-designs/': typeof PrintDesignsIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/branded-gifts'
    | '/cart'
    | '/checkout'
    | '/corporate-branding'
    | '/fabric-printing'
    | '/made-to-order'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reviews'
    | '/shipping'
    | '/sizing-framing'
    | '/terms-and-conditions'
    | '/checkout/success'
    | '/print-designs/$slug'
    | '/shop/$slug'
    | '/print-designs/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/branded-gifts'
    | '/cart'
    | '/checkout'
    | '/corporate-branding'
    | '/fabric-printing'
    | '/made-to-order'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reviews'
    | '/shipping'
    | '/sizing-framing'
    | '/terms-and-conditions'
    | '/checkout/success'
    | '/print-designs/$slug'
    | '/shop/$slug'
    | '/print-designs'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/branded-gifts'
    | '/cart'
    | '/checkout'
    | '/corporate-branding'
    | '/fabric-printing'
    | '/made-to-order'
    | '/privacy-policy'
    | '/refund-policy'
    | '/reviews'
    | '/shipping'
    | '/sizing-framing'
    | '/terms-and-conditions'
    | '/checkout/success'
    | '/print-designs/$slug'
    | '/shop/$slug'
    | '/print-designs/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrandedGiftsRoute: typeof BrandedGiftsRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CorporateBrandingRoute: typeof CorporateBrandingRoute
  FabricPrintingRoute: typeof FabricPrintingRoute
  MadeToOrderRoute: typeof MadeToOrderRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ReviewsRoute: typeof ReviewsRoute
  ShippingRoute: typeof ShippingRoute
  SizingFramingRoute: typeof SizingFramingRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  PrintDesignsSlugRoute: typeof PrintDesignsSlugRoute
  ShopSlugRoute: typeof ShopSlugRoute
  PrintDesignsIndexRoute: typeof PrintDesignsIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branded-gifts': {
      id: '/branded-gifts'
      path: '/branded-gifts'
      fullPath: '/branded-gifts'
      preLoaderRoute: typeof BrandedGiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-branding': {
      id: '/corporate-branding'
      path: '/corporate-branding'
      fullPath: '/corporate-branding'
      preLoaderRoute: typeof CorporateBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fabric-printing': {
      id: '/fabric-printing'
      path: '/fabric-printing'
      fullPath: '/fabric-printing'
      preLoaderRoute: typeof FabricPrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/made-to-order': {
      id: '/made-to-order'
      path: '/made-to-order'
      fullPath: '/made-to-order'
      preLoaderRoute: typeof MadeToOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sizing-framing': {
      id: '/sizing-framing'
      path: '/sizing-framing'
      fullPath: '/sizing-framing'
      preLoaderRoute: typeof SizingFramingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/print-designs/': {
      id: '/print-designs/'
      path: '/print-designs'
      fullPath: '/print-designs/'
      preLoaderRoute: typeof PrintDesignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-designs/$slug': {
      id: '/print-designs/$slug'
      path: '/print-designs/$slug'
      fullPath: '/print-designs/$slug'
      preLoaderRoute: typeof PrintDesignsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrandedGiftsRoute: BrandedGiftsRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CorporateBrandingRoute: CorporateBrandingRoute,
  FabricPrintingRoute: FabricPrintingRoute,
  MadeToOrderRoute: MadeToOrderRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ReviewsRoute: ReviewsRoute,
  ShippingRoute: ShippingRoute,
  SizingFramingRoute: SizingFramingRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  PrintDesignsSlugRoute: PrintDesignsSlugRoute,
  ShopSlugRoute: ShopSlugRoute,
  PrintDesignsIndexRoute: PrintDesignsIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
